project:
  type: website
  output-dir: ./docs
  
output:
  html_document:
    toc: yes
    toc_float: yes
    toc_depth: 2
    theme: lumen
    highlight: tango
    df_print: paged
    lib_dir: site_libs
    self_contained: no
    
# All icons were obtained from https://icons.getbootstrap.com/
website:   
  title: "MTH 142 Online"
  #favicon: /gfx/220.png
  
  navbar:
    
    right:
    - text: lectures
      href: index.qmd
    - text: MTH_142_files_for_students
      href: MTH_142_files_for_students.zip
  
  page-footer:
    right: 
    - text: credits
      href: credits.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true



